### ISSUE TITLE
New OWA - onSend support

### ISSUE THREAD

**Issue by sourabhkrishna** [OfficeDev/Outlook-Add-in-On-Send#10]
For the new owa I see the on send addin work without setting the OnSendAddinsEnabled to true , will this be a default roll out feature? And does classic web owa and new owa use different policy under the hood ?

**Comment by ElizabethSamuel-MSFT** [comment]
@sourabhkrishna Perhaps the [on-send article](https://docs.microsoft.com/outlook/add-ins/outlook-on-send-addins) can help answer your questions.
