### ISSUE TITLE
On-Send Not Triggering on Windows Outlook 2016

### ISSUE THREAD

**Issue by vardaro** [OfficeDev/Outlook-Add-in-On-Send#13]
Using the [on-send add-in tutorial](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins?tabs=windows) I'm attempting to configure execution on send in Windows Outlook 2016.

I've followed the instructions configuring the **Disable send when web extensions can't load** setting in **gpedit.msc**

When I create and send an email containing `blockedwork`, the event will trigger properly on Office365 web, but not on the windows app. I'm wondering if there additional steps involved in getting the extension working on Windows native?

Thanks,

Anthony

**Comment by ElizabethSamuel-MSFT** [comment]
@vardaro Thanks for your question.

At present, the on-send feature is in requirement set 1.8 and requires the newer builds of Windows Outlook available with an Office 365 subscription, but isn't available in one-time purchase versions (see the [server/client section of the requirement set support page](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#requirement-sets-supported-by-exchange-servers-and-outlook-clients) for more details).

Let us know if you need further info about this.

Thanks.
