### ISSUE TITLE
On Send won't work with dialog

### ISSUE THREAD

**Issue by nitro-marky** [OfficeDev/Outlook-Add-in-On-Send#15]
I'm using the on send event with Outlook Add Ins to show a dialog box confirming if the user wants to log the email or not. But it seems to be incompatible to use the On Send with dialogs. When I can get an email to send the send button becomes disabled, this can also happen on no and cancel. I don't understand why there isn't a basic template like the discard dialog that pops up. I just need to modify that for my needs.

Before I post all of the code has anyone else had this problem?

**Comment by nitro-marky** [comment]
`<?xml version="1.0" encoding="UTF-8"?>

<OfficeApp 
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" 
          xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" 
          xsi:type="MailApp">

  

  
  <Id></Id>

  
  <Version>1.0.0.0</Version>
  <ProviderName></ProviderName>
  <DefaultLocale>en-GB</DefaultLocale>
  
  <DisplayName DefaultValue="Research Distribution" />
  <Description DefaultValue="Distribution Tool"/>
  <IconUrl DefaultValue="~remoteAppUrl/Images/icon64.png"/>

  <SupportUrl DefaultValue="" />
  
  <AppDomains>
    <AppDomain>AppDomain1</AppDomain>
    <AppDomain>AppDomain2</AppDomain>
    <AppDomain>AppDomain3</AppDomain>
  </AppDomains>
  
  
  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="~remoteAppUrl/MessageRead.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.3">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">

          <DesktopFormFactor>
            
            <FunctionFile resid="functionFile" />
            <ExtensionPoint xsi:type="Events">
              <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="MessageSent" />
            </ExtensionPoint>
            
            <ExtensionPoint xsi:type="MessageComposeCommandSurface">
              
              <OfficeTab id="TabDefault">
                
                <Group id="msgReadGroup">
                  <Label resid="groupLabel" />
                  
                  <Control xsi:type="Button" id="msgReadOpenPaneButton">
                    <Label resid="paneReadButtonLabel" />
                    <Supertip>
                      <Title resid="paneReadSuperTipTitle" />
                      <Description resid="paneReadSuperTipDescription" />
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="icon16" />
                      <bt:Image size="32" resid="icon32" />
                      <bt:Image size="80" resid="icon80" />
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="messageReadTaskPaneUrl" />
                    </Action>
                  </Control>
                  
                </Group>
              </OfficeTab>
            </ExtensionPoint>
            
          </DesktopFormFactor>
        </Host>
      </Hosts>

      <Resources>
        <bt:Images>
          <bt:Image id="icon16" DefaultValue="~remoteAppUrl/Images/icon16.png"/>
          <bt:Image id="icon32" DefaultValue="~remoteAppUrl/Images/icon32.png"/>
          <bt:Image id="icon80" DefaultValue="~remoteAppUrl/Images/icon80.png"/>
        </bt:Images>
        <bt:Urls>
          <bt:Url id="functionFile" DefaultValue="~remoteAppUrl/Functions/FunctionFile.html"/>
          <bt:Url id="messageReadTaskPaneUrl" DefaultValue="~remoteAppUrl/Distro.cshtml"/>
        </bt:Urls>
        <bt:ShortStrings>
          <bt:String id="groupLabel" DefaultValue="My Add-in Group"/>
          <bt:String id="customTabLabel"  DefaultValue="Attach Research"/>
          <bt:String id="paneReadButtonLabel" DefaultValue="Research Distribution"/>
          <bt:String id="paneReadSuperTipTitle" DefaultValue="Get all properties"/>
        </bt:ShortStrings>
        <bt:LongStrings>
          <bt:String id="paneReadSuperTipDescription" DefaultValue="Opens the Research Distribution Tool."/>
        </bt:LongStrings>
      </Resources>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
`

**Comment by nitro-marky** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<OfficeApp 
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" 
          xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" 
          xsi:type="MailApp">

  

  
  <Id>c3a3882d-4880-4e4f-9eeb-8098dc2d7d70</Id>

  
  <Version>1.0.0.0</Version>
  <ProviderName></ProviderName>
  <DefaultLocale>en-GB</DefaultLocale>
  
  <DisplayName DefaultValue="Research Distribution" />
  <Description DefaultValue="Distribution Tool"/>
  <IconUrl DefaultValue="~remoteAppUrl/Images/icon64.png"/>

  <SupportUrl DefaultValue="https://www.arete.net" />
  
  <AppDomains>
    <AppDomain>AppDomain1</AppDomain>
    <AppDomain>AppDomain2</AppDomain>
    <AppDomain>AppDomain3</AppDomain>
  </AppDomains>
  
  
  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="~remoteAppUrl/MessageRead.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.3">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">

          <DesktopFormFactor>
            
            <FunctionFile resid="functionFile" />
            <ExtensionPoint xsi:type="Events">
              <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="MessageSent" />
            </ExtensionPoint>
            
            <ExtensionPoint xsi:type="MessageComposeCommandSurface">
              
              <OfficeTab id="TabDefault">
                
                <Group id="msgReadGroup">
                  <Label resid="groupLabel" />
                  
                  <Control xsi:type="Button" id="msgReadOpenPaneButton">
                    <Label resid="paneReadButtonLabel" />
                    <Supertip>
                      <Title resid="paneReadSuperTipTitle" />
                      <Description resid="paneReadSuperTipDescription" />
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="icon16" />
                      <bt:Image size="32" resid="icon32" />
                      <bt:Image size="80" resid="icon80" />
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="messageReadTaskPaneUrl" />
                    </Action>
                  </Control>
                  
                </Group>
              </OfficeTab>
            </ExtensionPoint>
            
          </DesktopFormFactor>
        </Host>
      </Hosts>

      <Resources>
        <bt:Images>
          <bt:Image id="icon16" DefaultValue="~remoteAppUrl/Images/icon16.png"/>
          <bt:Image id="icon32" DefaultValue="~remoteAppUrl/Images/icon32.png"/>
          <bt:Image id="icon80" DefaultValue="~remoteAppUrl/Images/icon80.png"/>
        </bt:Images>
        <bt:Urls>
          <bt:Url id="functionFile" DefaultValue="~remoteAppUrl/Functions/FunctionFile.html"/>
          <bt:Url id="messageReadTaskPaneUrl" DefaultValue="~remoteAppUrl/Distro.cshtml"/>
        </bt:Urls>
        <bt:ShortStrings>
          <bt:String id="groupLabel" DefaultValue="My Add-in Group"/>
          <bt:String id="customTabLabel"  DefaultValue="Attach Research"/>
          <bt:String id="paneReadButtonLabel" DefaultValue="Research Distribution"/>
          <bt:String id="paneReadSuperTipTitle" DefaultValue="Get all properties"/>
        </bt:ShortStrings>
        <bt:LongStrings>
          <bt:String id="paneReadSuperTipDescription" DefaultValue="Opens the Research Distribution Tool."/>
        </bt:LongStrings>
      </Resources>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>

**Comment by ElizabethSamuel-MSFT** [comment]
Related issue: https://github.com/OfficeDev/office-js-docs-pr/issues/1403
