### ISSUE TITLE
OnSend fired twice after attachment reminder

### ISSUE THREAD

**Issue by MhdTlb** [OfficeDev/Outlook-Add-in-On-Send#3]
If I include the word "attachment" in the email body and I click Send button, `OnSend` event is fired once and a pop-up modal window shows up with this message: 

> **Attachment reminder** 
> You may have forgotten to attach a file.

 with **Send** and **Don't send** buttons. If click **Send**, `OnSend` event get fired twice: 2 times after clicking `Send` button within attachment reminder. I was expecting only one event like the first **Send** (before attachment reminder pop-up).

**Comment by siewmoi** [comment]
Thanks for reporting this.  It has been fixed.
