### ISSUE TITLE
OnSend feature doesn't work in Office 2016 for Windows Outlook

### ISSUE THREAD

**Issue by bolyb** [OfficeDev/Outlook-Add-in-On-Send#4]
All other features of a normal Office Web Add In seem to work in the Office 2016 for Windows desktop version of Outlook as well. The sample application works correctly in the Office 365 Web Inbox, however it does not work in the Outlook desktop application. Is there any way to perform a function when an email is sent either in the Office 365 Web email client or the Outlook desktop application?

**Comment by bolyb** [comment]
Already documented [here](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins), it would be nice to know when this can be expected to be released for the desktop version though.

**Comment by jasonjoh** [comment]
We don't have a timeline to share on this yet. Keep an eye on https://dev.office.com/blogs for announcements.
