### ISSUE TITLE
Sample code not working on Outlook Office 365 Web App & Mac 

### ISSUE THREAD

**Issue by amrfarid140** [OfficeDev/Outlook-Add-in-On-Send#5]
I have tried this sample on both Outlook Office 365 Web App & Mac but it doesn't work. I can see the add-ins being added successfully but email send blocking is not happening. 

I have tested the server configuration by adding the XML through a URL and via file upload. 

- Is there a different configuration scenario for Outlook Office 365? 
- What is the best way to debug add-ins and understand failures?
- Why is this sample not working on Outlook Office 365?

Thanks !

**Comment by giulioambrogi** [comment]
Hi @amrfarid140 did you manage to use the code sample in the end?
I'm trying to use it on the web app, but doesn't seem to work.

@microsoftopensource  any update on that issue?

**Comment by rexcalibur** [comment]
Hi, i'm trying to test this add-in also but to no avail.

I was able to install it into Office365 but it doesn't seem to catch the email without the subject and didn't add the default cc email, and send it anyway.

Any update on this issue? Thanks.

**Comment by siewmoi** [comment]
Hi,
The on send feature is currently supported for Outlook on the web in Office 365 only.

The software engineer and I ran this code sample and it's working as expected.   Did you deploy it to a trusted web server and set your Outlook on the web mailbox policy to enable the on send feature?    By default, the on send functionality is disabled. 

Add-ins for Outlook on the web that use the on send feature will run for users who are assigned an Outlook on the web mailbox policy that has the OnSendAddinsEnabled flag set to true. You can enable on send by running Exchange Online PowerShell cmdlets. To learn what cmdlets to run, see lInstalling Outlook add-ins that use on send](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins#installing-outlook-add-ins-that-use-on-send).

**Comment by ElizabethSamuel-MSFT** [comment]
If you are still facing an issue after trying these suggestions, please reactivate or open a new issue. Thanks.
