### ISSUE TITLE
When will feature be available for Mac and Windows?

### ISSUE THREAD

**Issue by rickgoud** [OfficeDev/Outlook-Add-in-On-Send#6]
Hi guys.
This great feature was released now nearly a year ago for OWA. Is was then send that other platforms would follow soon. I would expect it to be already available after this time. Is there any information about this? I can find it nowhere.

Thanks!
Rick

**Comment by jasonjoh** [comment]
No, sorry. This is not available in any other clients yet. We are aware of the need for this and we are working on it. I don't have any guesses as to when we'll have more concrete news for you on this.

**Comment by Borkason** [comment]
@jasonjoh it would be nice if you could update this issue once the feature is available for Outlook 2016.

**Comment by aksswami** [comment]
Is there any update on this? For Mac and windows?

**Comment by ElizabethSamuel-MSFT** [comment]
Per the [article](https://docs.microsoft.com/outlook/add-ins/outlook-on-send-addins) about this feature, this feature has not yet been implemented for other platforms.
